import json

notebook = {
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "!git clone -b kaggle-implementation --single-branch https://github.com/nhanbayern/1003_EPA-Project_UIT.git\n",
    "import sys\n",
    "import os\n",
    "sys.path.append('/kaggle/working/1003_EPA-Project_UIT/transformer based')\n",
    "os.makedirs('/kaggle/working/results/all_predictions', exist_ok=True)\n",
    "os.makedirs('/kaggle/working/results/comparison_metrics', exist_ok=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import torch\n",
    "from torch.utils.data import DataLoader\n",
    "from dataset import VolatilityDataset\n",
    "from models import VanillaTransformer, Autoformer, Informer, Reformer\n",
    "from utils import calculate_fixed_nu, StudentTNLLLoss, calc_mse, calc_mae, calc_qlike\n",
    "import glob\n",
    "from pathlib import Path\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "DATA_DIR = '/kaggle/input/datasets/trnhngv/historical-price'\n",
    "HORIZONS = [1, 3, 5, 10, 21]\n",
    "EVAL_INDICES = [0, 2, 4, 9, 20] # Indices corresponding to the horizons in the 21-length output\n",
    "BATCH_SIZE = 32\n",
    "EPOCHS = 30\n",
    "LR = 1e-3\n",
    "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print('Using device:', DEVICE)\n",
    "\n",
    "# Table I Splits: (Train, Val, Test)\n",
    "SPLITS = {\n",
    "    'DAX_40': (1983, 1104, 972),\n",
    "    'Euronext_100': (2005, 1115, 979),\n",
    "    'IBEX_35': (1815, 1362, 923),\n",
    "    'KOSPI_Index': (1944, 1109, 881),\n",
    "    'Nikkei_225': (1677, 1174, 1062),\n",
    "    'SMI': (1987, 1135, 901),\n",
    "    'S&P_500': (1988, 1109, 927),\n",
    "    'VN30': (1971, 1096, 925),\n",
    "    'VN-Index': (1964, 1103, 925)\n",
    "}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_model(model, train_loader, val_loader, nu):\n",
    "    criterion = StudentTNLLLoss(nu=nu)\n",
    "    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)\n",
    "    best_val_loss = float('inf')\n",
    "    patience = 5\n",
    "    patience_counter = 0\n",
    "    best_state = None\n",
    "    \n",
    "    for epoch in range(EPOCHS):\n",
    "        model.train()\n",
    "        train_loss = 0\n",
    "        for x, _, y_ret, _ in train_loader:\n",
    "            x, y_ret = x.to(DEVICE), y_ret.to(DEVICE)\n",
    "            optimizer.zero_grad()\n",
    "            pred_vol = model(x)\n",
    "            loss = criterion(pred_vol, y_ret)\n",
    "            loss.backward()\n",
    "            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
    "            optimizer.step()\n",
    "            train_loss += loss.item()\n",
    "            \n",
    "        model.eval()\n",
    "        val_loss = 0\n",
    "        with torch.no_grad():\n",
    "            for x, _, y_ret, _ in val_loader:\n",
    "                x, y_ret = x.to(DEVICE), y_ret.to(DEVICE)\n",
    "                pred_vol = model(x)\n",
    "                val_loss += criterion(pred_vol, y_ret).item()\n",
    "                \n",
    "        val_loss /= len(val_loader)\n",
    "        if val_loss < best_val_loss:\n",
    "            best_val_loss = val_loss\n",
    "            best_state = {k: v.cpu() for k, v in model.state_dict().items()}\n",
    "            patience_counter = 0\n",
    "        else:\n",
    "            patience_counter += 1\n",
    "            if patience_counter >= patience:\n",
    "                print(f'Early stopping at epoch {epoch}. Best Val Loss: {best_val_loss:.4f}')\n",
    "                break\n",
    "                \n",
    "    if best_state is not None:\n",
    "        model.load_state_dict(best_state)\n",
    "    return model\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def evaluate_and_save(model, test_loader, df, index_name, model_name):\n",
    "    model.eval()\n",
    "    model.to(DEVICE)\n",
    "    \n",
    "    results = []\n",
    "    with torch.no_grad():\n",
    "        for x, y_vol, y_ret, ts in test_loader:\n",
    "            x = x.to(DEVICE)\n",
    "            pred_vol = model(x)\n",
    "            \n",
    "            pred_vol = pred_vol.cpu().numpy()\n",
    "            y_vol = y_vol.numpy()\n",
    "            ts = ts.numpy()\n",
    "            \n",
    "            for i in range(len(ts)):\n",
    "                t = ts[i]\n",
    "                for j, h in enumerate(HORIZONS):\n",
    "                    idx = EVAL_INDICES[j]\n",
    "                    target_t = t + h - 1\n",
    "                    target_time = df['time'].iloc[target_t] if target_t < len(df) else None\n",
    "                    target_ret = df['log_return'].iloc[target_t] if target_t < len(df) else None\n",
    "                    \n",
    "                    if target_time is not None:\n",
    "                        results.append({\n",
    "                            'time': target_time,\n",
    "                            'log_return': target_ret,\n",
    "                            'horizon': h,\n",
    "                            'true_volatility': y_vol[i, idx],\n",
    "                            'predict_volatility': pred_vol[i, idx]\n",
    "                        })\n",
    "    \n",
    "    res_df = pd.DataFrame(results)\n",
    "    save_path = f'/kaggle/working/results/all_predictions/{index_name}_{model_name}_predictions.csv'\n",
    "    res_df.to_csv(save_path, index=False)\n",
    "    return res_df\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate_metrics_for_df(res_df, model_name, index_name):\n",
    "    metrics_list = []\n",
    "    for h in HORIZONS:\n",
    "        h_df = res_df[res_df['horizon'] == h]\n",
    "        if len(h_df) == 0: continue\n",
    "        \n",
    "        pred = h_df['predict_volatility'].values\n",
    "        target = h_df['true_volatility'].values\n",
    "        \n",
    "        mse = calc_mse(pred, target)\n",
    "        mae = calc_mae(pred, target)\n",
    "        qlike = calc_qlike(pred, target)\n",
    "        \n",
    "        metrics_list.append({\n",
    "            'index': index_name,\n",
    "            'metric': 'MSE',\n",
    "            'horizon': h,\n",
    "            model_name: mse\n",
    "        })\n",
    "        metrics_list.append({\n",
    "            'index': index_name,\n",
    "            'metric': 'MAE',\n",
    "            'horizon': h,\n",
    "            model_name: mae\n",
    "        })\n",
    "        metrics_list.append({\n",
    "            'index': index_name,\n",
    "            'metric': 'QLIKE',\n",
    "            'horizon': h,\n",
    "            model_name: qlike\n",
    "        })\n",
    "    return pd.DataFrame(metrics_list)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# MAIN LOOP\n",
    "all_metrics_dfs = []\n",
    "\n",
    "csv_files = glob.glob(f'{DATA_DIR}/*.csv')\n",
    "if len(csv_files) == 0:\n",
    "    print(\"WARNING: No CSV files found. Running mock logic for syntax check.\")\n",
    "    csv_files = ['mock_DAX_40.csv']\n",
    "\n",
    "for fpath in csv_files:\n",
    "    fname = Path(fpath).stem\n",
    "    index_name = fname.replace(' ', '_')\n",
    "    print(f'\\n========== Processing {index_name} ==========')\n",
    "    \n",
    "    if os.path.exists(fpath):\n",
    "        df = pd.read_csv(fpath)\n",
    "    else:\n",
    "        dates = pd.date_range('2010-01-01', periods=4059)\n",
    "        df = pd.DataFrame({'time': dates, 'close': np.random.randn(4059).cumsum() + 1000})\n",
    "        index_name = 'DAX_40'\n",
    "        \n",
    "    if 'log_return' not in df.columns:\n",
    "        df['log_return'] = np.log(df['close'] / df['close'].shift(1)) * 100.0\n",
    "        \n",
    "    df = df.dropna(subset=['log_return']).reset_index(drop=True)\n",
    "    \n",
    "    if index_name in SPLITS:\n",
    "        n_train, n_val, n_test = SPLITS[index_name]\n",
    "    else:\n",
    "        N = len(df)\n",
    "        n_train = int(N * 0.6)\n",
    "        n_val = int(N * 0.2)\n",
    "        n_test = N - n_train - n_val\n",
    "        \n",
    "    train_returns = df['log_return'].iloc[:n_train].values\n",
    "    nu = calculate_fixed_nu(train_returns)\n",
    "    print(f'Calculated NU for {index_name} (Train): {nu:.4f}')\n",
    "    \n",
    "    df_train = df.iloc[:n_train].copy()\n",
    "    df_val = df.iloc[max(0, n_train - 60) : n_train + n_val].copy()\n",
    "    df_test = df.iloc[max(0, n_train + n_val - 60) : ].copy()\n",
    "    \n",
    "    ds_train = VolatilityDataset(df_train, lookback=60, horizon=21)\n",
    "    ds_val = VolatilityDataset(df_val, lookback=60, horizon=21)\n",
    "    ds_test = VolatilityDataset(df_test, lookback=60, horizon=21)\n",
    "    \n",
    "    train_loader = DataLoader(ds_train, batch_size=BATCH_SIZE, shuffle=True)\n",
    "    val_loader = DataLoader(ds_val, batch_size=BATCH_SIZE, shuffle=False)\n",
    "    test_loader = DataLoader(ds_test, batch_size=BATCH_SIZE, shuffle=False)\n",
    "    \n",
    "    models_dict = {\n",
    "        'Vanilla': VanillaTransformer(),\n",
    "        'Autoformer': Autoformer(),\n",
    "        'Informer': Informer(),\n",
    "        'Reformer': Reformer()\n",
    "    }\n",
    "    \n",
    "    index_metrics_dfs = []\n",
    "    for m_name, model in models_dict.items():\n",
    "        print(f'--- Training {m_name} ---')\n",
    "        model.to(DEVICE)\n",
    "        model = train_model(model, train_loader, val_loader, nu)\n",
    "        \n",
    "        print(f'--- Evaluating {m_name} ---')\n",
    "        res_df = evaluate_and_save(model, test_loader, df_test, index_name, m_name)\n",
    "        \n",
    "        m_metrics = calculate_metrics_for_df(res_df, m_name, index_name)\n",
    "        index_metrics_dfs.append(m_metrics)\n",
    "        \n",
    "    merged_index_metrics = index_metrics_dfs[0]\n",
    "    for i in range(1, len(index_metrics_dfs)):\n",
    "        merged_index_metrics = pd.merge(merged_index_metrics, index_metrics_dfs[i], \n",
    "                                        on=['index', 'metric', 'horizon'], how='outer')\n",
    "    all_metrics_dfs.append(merged_index_metrics)\n",
    "\n",
    "if len(all_metrics_dfs) > 0:\n",
    "    final_metrics_df = pd.concat(all_metrics_dfs, ignore_index=True)\n",
    "    # Match user format comparison_metrics_tidy.csv\n",
    "    final_metrics_df.to_csv('/kaggle/working/results/comparison_metrics_tidy.csv', index=False)\n",
    "    print('\\nALL DONE! Metrics saved to /kaggle/working/results/comparison_metrics_tidy.csv')\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open(r'D:\\UIT\\1003_EPA_PROJECT\\1.0.0\\1003_EPA-Project_UIT\\transformer based\\kaggle_notebook.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)
